Beethoven/urls.py
from django.contrib import admin
from django.urls import path, include
from analiseProcessos import url 
from analiseProcessos import url as atividades_urls
from user.views import login_view, logout_view
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings
from compras import url as compras_urls

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include(atividades_urls)),
    path('login/', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('', include(compras_urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 # type: ignore

analiseProcessos/models.py
from django.db import models
from user.models import Empresa
from datetime import date, timedelta
import datetime

# Create your models here.

class Semana(models.Model):
    inicio = models.DateField()
    fim = models.DateField()
    numero = models.IntegerField()
    processos = models.IntegerField(default=0)
    analises = models.IntegerField(default=0)
    realizado = models.BooleanField(default=False)
    data = models.DateField(default=date.today)
    numeroNC = models.IntegerField(default=0)
    portaria = models.CharField(max_length=4, choices=[("SV","SV"), ('OIVA', 'OIVA'),("PP", 'PP')], default="SV", null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
            
    def __str__(self):
        return (f"Semana: {self.numero} - "+self.inicio.strftime("%d/%m/%y")+"-"+self.fim.strftime("%d/%m/%y")+' - '+self.empresa.nome)
   
class AnaliseProcessoSV(models.Model):
    semana = models.ForeignKey(Semana, on_delete=models.CASCADE)
    OS = models.IntegerField(help_text="Nº da OS", null=True)
    data = models.DateField(default=date.today)
    user = models.CharField(max_length=30, default="João")
    crlv = models.CharField(max_length=20, choices=[('A','A'),('R', 'R'),('NA', 'NA')], default="A", help_text="1)	CRLV ou CRV ou NF compra veículo – HABILITAÇÃO do condutor", null=True)
    decalque = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')], default="A", help_text="2)	DECALQUE do número do chassi;", null=True)
    vistoriaInicial = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')], default="A",  help_text="3)	FOR ADM 31 ORDEM DE SERVIÇO com a VISTORIA INICIAL;", null=True)
    verificaoEscopo = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="4)	Lista de verificação correta ao escopo, rastreável, com anotações corretas, correções conforme procedimento, com quantificáveis rastreado ao equipamento entre outros;", null=True)
    linhaInspecao = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="5)	Relatório da LINHA DE INSPEÇÃO, assinado por todos, 'A', com número de patrimônio, rastreavel ao veículo, equipamento calibrado entre outros;", null=True)
    opacidade = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="6)	Relatório de OPACIDADE, ANÁLISE DE GASES quando aplicável, assinado por todos, 'A', com número de patrimônio, rastreavel ao veículo, equipamento calibrado entre outros;", null=True)
    ruido = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="7)	Relatório de RUÍDO, quando aplicável, assinado por todos, 'A', com número de patrimônio, rastreavel ao veículo, equipamento calibrado entre outros;", null=True)
    naoConformidade = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="8)	Registro de NÃO CONFORMIDADE;", null=True)
    rasurasProcessos = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="9)	Verificar a existência de RASURAS NOS PROCESSOS;", null=True)
    registrosFotograficos = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')], default="A",help_text="10)	Registro fotográfico do EIXO (s) DIANTEIRO (s) e EIXO (s) TRASEIRO (s) do veículo e a banda de rodagem dos pneus dianteiros e pneus traseiros. A foto do eixo dianteiro deve ser tirada no sentido do eixo traseiro, a foto do eixo traseiro deve ser tirada no sentido do eixo dianteiro, quando houver um terceiro eixo, o registro fotográfico deve ser tirado no sentido do eixo traseiro; Registro fotográfico do Para todos os veículos com PARA-CHOQUE homologados, um (1) registro fotográfico da plaqueta de homologação do pára-choque; Registro fotográfico do transversal do PINO-REI e de sua MESA LIMPOS ou QUINTA RODA, quando aplicável; Registro fotográfico das LATERAIS DOS VEÍCULOS com as FAIXAS REFLETIVAS, quando aplicáveis; Registro fotográfico ALÍVIO DE PESO no eixo direcional em veículos pesados, quando aplicável; Registro fotográfico da TRASEIRA DO VEÍCULO na linha de inspeção mecanizada, que tenha possibilidade de leitura da PLACA de licença no RELATÓRIO DE INSPEÇÃO.Obs. Os registros fotográficos devem conter data e hora.", null=True)
    filmagem = models.CharField(max_length=2, choices=[('A','A'),('R', 'R'),('NA', 'NA')],default="A", help_text="11)	Filmagem de todas as etapas de inspeção, verificar calibragem de pneus, ensaio de regloscopio, verificação do sistema de sinalização, ensaio de opacidade e ruído, dentre outros, a filmagem deve conter data e horas no formato (DD/MM/AAAA) e (hh:mm:ss).", null=True)
    observacoes = models.TextField(help_text="Observações", null=True)
    realizado = models.BooleanField(default=False)
    NC = models.CharField(max_length=3, choices=[('Sim', 'Sim'),("Não","Não")], default="Não")
    
    def __str__(self):
        if self.realizado == True:
            return str(self.OS)
        else:
            return "Análise a realizar, clique em atualizar"
        
class Questao(models.Model):
    questao = models.CharField(max_length=200)
    portaria = models.CharField(max_length=4, choices=[("SV","SV"), ('OIVA', 'OIVA'),("PP", 'PP')], default="SV", null=True)
    titulo = models.CharField(max_length=200, null=True)
    numero = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.portaria) + ' - '+self.questao
    
class AnaliseProcesso(models.Model):
    semana = models.ForeignKey(Semana, on_delete=models.CASCADE)
    OS = models.IntegerField(help_text="Nº da OS", null=True)
    data = models.DateField(default=date.today)
    user = models.CharField(max_length=30, default="João")
    observacoes = models.TextField(help_text="Observações", null=True)
    realizado = models.BooleanField(default=False)
    NC = models.CharField(max_length=3, choices=[('Sim', 'Sim'),("Não","Não")], default="Não")
        
    def __str__(self):
        if self.realizado == True:
            return str(self.OS)
        else:
            return "Análise a realizar, clique em atualizar"
    
class AnaliseProcessoResposta(models.Model):
    resposta = models.CharField(max_length=200, choices=[('A','A'),('R', 'R'),('NA', 'NA')], default='A')
    analiseProcesso = models.ForeignKey(AnaliseProcesso, on_delete=models.CASCADE,  null=True)
    quest = models.ForeignKey(Questao, on_delete=models.CASCADE, null=True, related_name='questoes')
    

analiseProcessos/views.py
import datetime
import io
from user.models import UserProfile
from django.shortcuts import render, redirect
from analiseProcessos.forms import analiseForm
from .models import AnaliseProcesso, AnaliseProcessoResposta, AnaliseProcessoSV, Questao, Semana
from django.views.generic.edit import CreateView, UpdateView, View
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, FileResponse, HttpResponse
from .util.report import imprimirPDF
from django.http import FileResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

#As semanas serão realizados pelo updateModels
#As análises de processos, serão feitas através da pagina 'listSem/ + portaria' por exemplo listSem/OIVA
#Depois que inserir quantos foram os processos, quem abre a página é listProc


#listar todas as análises na semana.
class listSem(View):
    def get(self, request, portaria):  
        user = UserProfile.objects.filter(user=request.user).first()
        semana = Semana.objects.filter(empresa=user.empresa, portaria=portaria)
        return render(request, 'atividades/listSem.html', {'semanas':semana, 'portaria':portaria})    

#Listagem dos procedimentos, passa a semana para listar todos os procedimentos.
class listProc(LoginRequiredMixin ,View):
    def get(self, request, semana):
        #aqui precisa fazer uma seleção do usário/empresa
        data = {}
        semana = Semana.objects.get(id=int(semana))
        data['semana'] = semana
        data['analises'] = AnaliseProcesso.objects.filter(semana=semana)
        return render(request, 'atividades/listProc.html', data)     

#Criação de todas as análises críticas necessárias para aquela semana.
@login_required
def criaAnalisesProcessos(request):
    semana = Semana.objects.get(id=request.POST.get('semana_hidden'))
    processos = int(request.POST.get('processos'))
    #Se o usuário inserir 0, quer dizer que aquele período não teve inspeções
    if processos > 0:         
        nAnalises = round((int(processos)*0.05)+0.5)
        #inserir usuário da sessão:        
        user = request.user            
        analises = []
        for i in range(nAnalises):
            analise = AnaliseProcesso.objects.create(semana=semana, user=user)
            analises.append(analise)
            Semana.objects.filter(id=semana.id).update(processos=processos,analises=nAnalises) 
        return redirect('listProc-view', semana.id)     
    #é salvado a analise zerada e retorna para lista.
    else:
        Semana.objects.filter(id=request.POST.get('semana_hidden')).update(realizado= True)
        return redirect('listSem-view' , semana.portaria)
   
#Procedimento para realização do Cadastro
class RealizaAnaliseProcesso(View):
    def get(self, request, id):
        analise = AnaliseProcesso.objects.get(id=id)
        if analise.realizado:
            formularios = AnaliseProcessoResposta.objects.filter(analiseProcesso = analise)
            return render(request, 'atividades/updProc_edt.html', {'formulario':formularios, 'os':analise.OS, 'observacoes':analise.observacoes})
        else:
            formularios = Questao.objects.filter(portaria = analise.semana.portaria)       
        return render(request, 'atividades/updProc_cad.html', {'formulario':formularios})
    
    def post(self, request, id):
        analise = AnaliseProcesso.objects.get(id=id)       
        nc = 'Não'
        # melhorar o desempenho do primeiro registro, pensar como fazer isso.
        if not analise.realizado:             
            formularios = Questao.objects.filter(portaria = analise.semana.portaria)
            for formulario in formularios:
                form = AnaliseProcessoResposta.objects.create()                        
                form.analiseProcesso = analise
                form.resposta = request.POST.get(formulario.titulo)
                if form.resposta == 'R':
                    nc = 'Sim'
                form.quest = formulario                
                form.save()    
        else:
            respostas = AnaliseProcessoResposta.objects.filter(analiseProcesso=analise)
            for resposta in respostas:               
                if request.POST.get(resposta.quest.titulo) == 'R':
                    nc = 'Sim'
                AnaliseProcessoResposta.objects.filter(id=resposta.id).update(resposta=request.POST.get(resposta.quest.titulo))
        AnaliseProcesso.objects.filter(id=id).update(OS=request.POST.get('OS'), data=datetime.date.today(), realizado = True, NC = nc, observacoes=request.POST.get('observacoes'))
        analises = AnaliseProcesso.objects.filter(semana=analise.semana)
        #faz análise se existe processos em aberto ainda: tirar daqui      
        for ana in analises:
            realizado = ana.realizado        
        if(realizado):
            Semana.objects.filter(id=analise.semana.id).update(realizado= True,data=datetime.date.today())
        return redirect('listProc-view', semana=analise.semana.id)

#aqui quando eu insiro ou excluo uma análise de processos ele atualiza na semana.
@login_required
def atualizarNumerosProcessos(request):
    AnaliseProcessoSV.objects.filter(semana=request.POST.get('semana_hidden')).delete()
    Semana.objects.filter(id=request.POST.get('semana_hidden')).update(analises=0, processos=0,realizado=False)
    criaAnalisesProcessos(request, request.POST.get('semana_hidden'))
    return redirect('listSem-view')

#usei upd porque o usário não cria essas análises por OS, ele apenas diz quantas ele quer criar.
#obsoleto
class updProc(View):
    def get(self, request,id):
        analise = AnaliseProcessoSV.objects.get(id=id)
        form = analiseForm().iniciar(analise)     
        return render(request, 'atividades/updProc.html', {'form':form})
    
    def post(self, request, id):
        post = request.POST                
        analise = AnaliseProcessoSV.objects.get(id=id)
        #verificar se existe reprova e etc;
        nc = verificarNC(request)
        AnaliseProcessoSV.objects.filter(id=id).update(OS=post.get('OS'), crlv=post.get('crlv'),data=datetime.date.today(), decalque=post.get('decalque'), vistoriaInicial=post.get('vistoriaInicial'), verificaoEscopo=post.get('verificaoEscopo'),linhaInspecao=post.get('linhaInspecao'),opacidade=post.get('opacidade'),ruido=post.get('ruido'),naoConformidade=post.get('naoConformidade'),rasurasProcessos=post.get('rasurasProcessos'),registrosFotograficos=post.get('registrosFotograficos'),filmagem=post.get('filmagem'), observacoes=post.get('observacoes'), realizado= True, NC = nc ) 
        analises = AnaliseProcessoSV.objects.filter(semana=analise.semana)
        #faz análise se existe processos em aberto ainda: tirar daqui        
        for ana in analises:
            realizado = ana.realizado        
        if(realizado):
            Semana.objects.filter(id=analise.semana.id).update(realizado= True,data=datetime.date.today())
        return redirect('listProc-view', semana=analise.semana.id)
      
@login_required
def delProc(request, id):
    realizado = False
    ana = AnaliseProcesso.objects.filter(id=id).first()
    ana.delete()
    semana = Semana.objects.filter(id=ana.semana.id)
    analises = AnaliseProcesso.objects.filter(semana=ana.semana)     
    for ana in analises:
        realizado = ana.realizado    
    Semana.objects.filter(id=semana.id).update(realizado=realizado, analises=semana.analises-1)     
    return redirect('listProc-view', semana.id)

@login_required
def criarNovoProcessoIndividual(request,semana):
    semana = Semana.objects.get(id=semana)
    analise = AnaliseProcesso()
    analise.semana = semana  
    analise.save()
    Semana.objects.filter(id=semana.id).update(analises=semana.analises+1,realizado=False)
    return redirect('listProc-view', semana.id)

def report(request,id):
    semana = Semana.objects.get(id=id)    
    buffer = io.BytesIO()    
    ncs = qntdNC(semana)
    imprimirPDF(buffer,semana,request.user, ncs)
    buffer.seek(0)
    filename=semana.data
    return FileResponse(buffer, as_attachment=False, filename="Analise: "+str(semana.inicio)+" - "+str(semana.fim)+".pdf")

#esse é o home provisório do site, vou ter que ver como fazer isso de uma maneira mais desmembrada
def home(request):
    return render(request, 'user/index.html')

def verificarNC(request):
    nc = 'Não'
    if(request.POST.get('crlv') == 'R'):
        nc = 'Sim'

    if(request.POST.get('decalque') == 'R'):
        nc = 'Sim'

    if(request.POST.get('vistoriaInicial') == 'R'):
        nc = 'Sim'

    if(request.POST.get('verificaoEscopo') == 'R'):
        nc = 'Sim'

    if(request.POST.get('linhaInspecao') == 'R'):
        nc = 'Sim'

    if(request.POST.get('opacidade') == 'R'):
        nc = 'Sim'

    if(request.POST.get('ruido') == 'R'):
        nc = 'Sim'

    if(request.POST.get('naoConformidade') == 'R'):
        nc = 'Sim'

    if(request.POST.get('rasurasProcessos') == 'R'):
        nc = 'Sim'

    if(request.POST.get('registrosFotograficos') == 'R'):
        nc = 'Sim'

    if(request.POST.get('filmagem') == 'R'):
        nc = 'Sim'
    return nc

def qntdNC(semana):
    nc = 0
    analises = AnaliseProcesso.objects.filter(semana=semana.id) 
    for analise in analises:
        respostas = AnaliseProcessoResposta.objects.filter(analiseProcesso=analise)
        for resposta in respostas:
            if resposta == "R":
                nc = nc+1
    return nc 

#Criar analises de processos na semana correta.
class cadSem(View):
    def get(self, request,id):
        model = Semana.objects.get(id=id)
        form = ""
        return render(request, 'atividades/cadSemana.html', {'semana':model, "form":form})
            
    def post(self, request,id):
        data = {}          
        post = request.POST        
        #faz a busca no banco para verificar os dados da semana

analiseProcessos/templates/atividades/cadSemana.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %} Cadastro Análise Crítica {% endblock%}

{% block main %}    
    <br/>
    {% if not semana.numero  %}
    <div class="row">
        <div class="col-12">        
            <h3>Fazer análise de crítica de processos</h3>
            <form action="" name="formProcesso" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}                      
                <h4>Semana: {{semana.inicio|date:"d/m/y"}} a <td>{{semana.fim|date:"d/m/y"}}/h4><br/>
                <br/>
                <label>Número de processos na semana</label><br/>
                <input name="numProcessos" value="numProcessos" type="number" required class="input input"/>                
                <br/><br/>
                <input type="submit" class="btn btn-info" required="required" value="Criar"/>
            </form>
        </div>
    </div>  
    {% endif %}
    <br/>
{% endblock %}

analiseProcessos/templates/atividades/cadastroAnalise.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %} Novo Cliente {% endblock%}

{% block main %}    
    <br/>
    <div class="row">
        <div class="col-12">        
            <h3>Fazer análise de processos</h3>
            <form action="" name="formProcesso" method="post"  enctype="multipart/form-data">
                {% csrf_token %}         
                <label>Selecione a semana:</label><br/>
                <select name="selSemana">
                    {% for semana in semanas %}
                        <option value="{{semana.numero}}">Semana: {{semana.numero}} - {{semana.inicio|date:"d/m/y"}} a {{semana.fim|date:"d/m/y"}}</option>
                    {% endfor %}             
                </select>
                <br/><br/>
                <label>Número de processos na semana</label><br/>
                <input name="numProcessos" value="numProcessos" type="number" class="input input"/>
                <br/><br/>
                <input type="submit" class="btn btn-info" required="required" value="Criar"/>
            </form>
        </div>
    </div>    
{% endblock %}

analiseProcessos/templates/atividades/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <br/>
    <div class="row">
        <div class="col-5">
            <a href="{% url 'listSem-view' %}">Análise Crítica de Processos</a>
        </div>       
    </div>       
{% endblock %}

analiseProcessos/templates/atividades/listProc.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load mathfilters %}

{% block title %}Análise de processos{% endblock%}

{% block main %}    

{% if semana.numero %}
      <div class="row">
          <div class="col-12">
            <div class="table-title col-12">
              <div class="row">
                  <div class="col-6">
                      <h2>Análises de <b>Processos</b></h2>
                  </div>
                  <div class="col-6">
                      <a href="{% url 'newProc-view' semana.id %}">
                      <button class="btn btn-new">
                          <i class="fa fa-plus"></i> Novo
                      </button>
                      </a>
                  </div>
              </div>
          </div>          
            <table class="table text-center table-striped">
                <thead>
                    <tr>
                      <th scope="col">OS</th>                      
                      <th scope="col">NC</th>
                      <th scope="col">Atualizar</th>                      
                      <th scope="col">Excluir</th>                      
                    </tr>
                  </thead>
                  <tbody>
                {% for analise in analises %}                
                  <tr>
                    <th scope="row">{{ analise }}</th>                    
                    <td>{{ analise.NC }}</td>
                    <td><a href="{% url 'analiseProcesso-view' analise.id %}"><i class="fas fa-sync personal_icons"></i></a></td>                    
                    <td> <a href="{% url 'delProc-view' analise.id %}"  
                      onclick="return confirm('Você tem certeza que quer deletar ?')">
                      <i class="fa-solid fa-trash delete-icon"></i>
                    </td>              
                  </tr>                  
                {% endfor %}
                </tbody>
              </table>
              <a href="{% url 'listSem-view' semana.portaria %}">Retornar para lista de semanas clique aqui!<a/>
        </div>
    </div>
    {% endif %}
{% endblock %}

analiseProcessos/templates/atividades/ok.html
{{ id }}

analiseProcessos/templates/atividades/updProc.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Cadastrar Análise{% endblock%}

{% block main %}    
    <br/>  
    <div class="row">
        <div class="col-12">        
            <h3>Fazer análise crítica de processos</h3>            
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}      
                {{ form|bootstrap }}    
                <input type="submit" class="btn btn-info" value="Salvar"/>             
            </form>
            <br/>
        </div>
    </div>       
{% endblock %}

analiseProcessos/templates/atividades/updProc_cad.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load mathfilters %}
{% block title %}Gerenciar Análises de Processo{% endblock%}

{% block main %}   
    <br/>
    <div class="row">
        <div class="col-12">        
            <h3>Formulário Analise Crítica</b></h3>
            <form action="" name="formCompras" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}   
                <div class="form-group">
                    <label class="control-label  " for="id_OS">Ordem de Serviço: </label>
                    <div class=" ">
                        <input type="number" name="OS" class=" form-control" required="" id="id_OS">
                    </div>
                </div>               
                {% for form in formulario %}
                    <div class="form-group">
                        <label class="control-label  " for="id_{{ form.titulo}}">{{form.titulo}}</label>
                        <div class="">
                            <select name="{{form.titulo}}" class="has-popover form-control" data-content="{{ form.questao }}" data-placement="right" data-container="body" id="id_{{form.titulo}}">
                            <option value="A" selected="">A</option>
                            <option value="R">R</option>
                            <option value="NA">NA</option>
                            </select>
                            <p class="">
                                {{ form.questao }}
                            </p>
                        </div>
                    </div>                    
                {% endfor %}
                <div class="form-group">
                    <label class="control-label  " for="id_observacoes">Observacoes</label>
                    <div class=" ">
                        <textarea name="observacoes" cols="40" rows="5" class=" form-control" id="id_observacoes"></textarea>
                    </div>
                </div>
                <input type="submit" class="btn btn-info" required="required" value="Salvar"/>
            </form>
        </div>
    </div>  
    <br/>
</div>
{% endblock %}

analiseProcessos/templates/atividades/updProc_edt.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load mathfilters %}
{% block title %}Gerenciar Análises de Processo{% endblock%}

{% block main %}   
    <br/>
    <div class="row">
        <div class="col-12">        
            <h3>Formulário Analise Crítica</b></h3>
            <form action="" name="formCompras" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}   
                <div class="form-group">
                    <label class="control-label  " for="id_OS">Ordem de Serviço: </label>
                    <div class=" ">
                        <input type="number" name="OS" class=" form-control" required="" id="id_OS" value='{{ os }}'>
                    </div>
                </div>               
                {% for form in formulario %}
                <div class="form-group">
                    <label class="control-label  " for="id_{{ form.quest.titulo}}">{{form.quest.titulo}}</label>
                    <div class="">
                        <select name="{{form.quest.titulo}}" class="has-popover form-control" data-content="{{ form.quest.questao }}" data-placement="right" data-container="body" id="id_{{form.titulo}}">
                        <option value="A" {%if form.resposta == 'A' %}selected{%endif%}>A</option>
                        <option value="R" {%if form.resposta == 'R' %}selected{%endif%}>R</option>
                        <option value="NA" {%if form.resposta == 'NA' %}selected{%endif%}>NA</option>
                        </select>
                        <p class="">
                        {{ form.quest.questao }}
                        </p>
                    </div>
                </div>
                {% endfor %}
                <div class="form-group">
                    <label class="control-label  " for="id_observacoes">Observacoes</label>
                    <div class=" ">
                        <textarea name="observacoes" cols="40" rows="5" class=" form-control" id="id_observacoes">{{ observacoes }}</textarea>
                    </div>
                </div>
                <input type="submit" class="btn btn-info" required="required" value="Salvar"/>
            </form>
        </div>
    </div>  
    <br/>
</div>
{% endblock %}